### ISSUE TITLE
11ty migration

### ISSUE THREAD

**Issue by kevinmpowell** [EightShapes/eightshapes-com#154]
## Todos
In no particular order
* [x] Migrate content out of `systemsposts.json` into front matter on each individual article. A manual, repetitive process (possibly automate migration?)
* [x] Migrate `.njk` articles to `.md`
  * Remove unneeded `{% filter markdown %}` blocks
  * Replace `title_image_path` variable with auto-generated `page.fileSlug`
  * add escom import statement if escom components are used: `{% import '../_includes/escom.njk' as escom with context %}`
  * Manually check for errors, specifically with markdown code blocks with three backticks
  * Remove `main_article` block
  * Change `date_published` to `date` in front matter
  * Remove `date_updated` - it's only used by one article currently and may be a typo
  * Remove `read_duration` - it's automatically calculated based on content length using an 11ty plugin
* [x] SCSS compiler
* [ ] test/rewrite deploy script
* [ ] Remove unneeded gulp
* [x] replace sass-lint with style lint
* [ ] Add eslint & style lint pre-commit hooks with husky
* [ ] Find a way to set up redirects so google analytics data isn't lost
* [ ] Improve styling of markdown code blocks:  
<img width="733" alt="image" src="https://user-images.githubusercontent.com/979463/77585682-e1d09a00-6eb2-11ea-99b8-f8956105bd87.png">

* [x] Fix `components.index.njk` to pull from 11ty's tags instead of `systemsposts.json` : 
<img width="951" alt="image" src="https://user-images.githubusercontent.com/979463/77588186-60c7d180-6eb7-11ea-87d8-99dd044b0e76.png">
